### ISSUE TITLE
Replace access denied response

### ISSUE THREAD

**Issue by Enado95** [v-ladynev/keycloak-nodejs-example#12]
Is there a way to return a different response from the `403` `Access denied`?
I would want to return my own error object.

**Comment by v-ladynev** [comment]
@Enado95 I think you have to configure `keycloak-connect` for that
https://www.keycloak.org/docs/latest/securing_apps/index.html#_nodejs_adapter

You can start from here
https://github.com/v-ladynev/keycloak-nodejs-example/blob/master/lib/keyCloakService.js#L41

**Comment by Enado95** [comment]
Works!! Much appreciated.
