### ISSUE TITLE
Issue when try add new user

### ISSUE THREAD

**Issue by NomiasSR** [v-ladynev/keycloak-nodejs-example#4]
Hello for all,

After doing all configurations my example is working fine, but when I try add a new user the system shown this message on the bottom of the screen:
<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /auth/realms/master/protocol/openid-connect/token was not found on this server.</p>\n<hr>\n<address>Apache/2.4.33 (Win64) PHP/7.2.4 Server at localhost Port 8080</address>\n</body></html>\n

I would like to know how can I do to fix this issue or if keycloak has some external API when I could create new users.

Regards

Paulo

**Comment by v-ladynev** [comment]
@NomiasSR Hello. Yes `Keycloak` has REST API to create new users. You can find an example here
https://github.com/v-ladynev/keycloak-nodejs-example/blob/master/lib/adminClient.js#L35

Your error means that you specified an incorrect `URL`. The `URL` for this example here
https://github.com/v-ladynev/keycloak-nodejs-example/blob/master/keycloak.json#L3

Also, It will be better if you try to create a new user using REST API Client like `Postman` and after that will continue to work with the code.
