### ISSUE TITLE
REFRESH TOKEN

### ISSUE THREAD

**Issue by ellik95** [v-ladynev/keycloak-nodejs-example#8]
Hello,
Does your example support refresh token or do you know how can I implement this?
Thank you

**Comment by v-ladynev** [comment]
@ellik95 JWT token that is returned by Keycloak has `refresh_token`
https://github.com/v-ladynev/keycloak-nodejs-example#what-happens-with-custom-login

`keycloak-nodejs-example` uses 
https://github.com/keycloak/keycloak-nodejs-connect library.

This library supports refreshing of the `access_token`
https://github.com/keycloak/keycloak-nodejs-connect/blob/master/middleware/auth-utils/grant-manager.js#L217

**Comment by ellik95** [comment]
Thank you for your answer!

**Comment by v-ladynev** [comment]
@ellik95 Always happy to help.
